#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

exec s6-setuidgid hotio "${APP_DIR}/bin/calibre-server" --enable-auth --auth-mode="${AUTH_MODE}" --port 8081 --url-prefix "${URL_PREFIX}" "${CONFIG_DIR}"
