#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "Ensuring library exists"
s6-setuidgid hotio "${APP_DIR}/bin/calibredb" --with-library "${BOOK_DIR}" list --limit 1 > /dev/null

# Make sure users exist
if [ -n "${USER+x}" ] && [ -n "${PASSWORD+x}" ]; then
    USERS=$(s6-setuidgid hotio "${APP_DIR}/bin/calibre-server" --manage-users -- list)
    if [[ "${USERS}" == *"${USER}"* ]]; then
        echo "Syncing password for user ${USER}"
        s6-setuidgid hotio "${APP_DIR}/bin/calibre-server" --manage-users -- chpass "${USER}" "${PASSWORD}"
    else
        echo "Adding user ${USER}"
        s6-setuidgid hotio "${APP_DIR}/bin/calibre-server" --manage-users -- add "${USER}" "${PASSWORD}"
    fi
fi
